"""init

Revision ID: b4eb272298a4
Revises: 
Create Date: 2025-09-24 11:43:47.938001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4eb272298a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharma', sa.String(length=120), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('agency', sa.String(length=120), nullable=True),
    sa.Column('indication', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('channel', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_uid', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('use_case', sa.Enum('RFP', 'PROGRAM_MAPPING', 'INTERNAL', name='usecaseenum'), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('file_ext', sa.String(length=16), nullable=True),
    sa.Column('uploaded_by', sa.String(length=120), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_uid')
    )
    op.create_table('client_target_lists',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('target_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['target_list_id'], ['target_lists.id'], ),
    sa.PrimaryKeyConstraint('client_id', 'target_list_id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_uid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('flight_start', sa.Date(), nullable=True),
    sa.Column('flight_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_uid')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_target_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('target_list_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['target_list_id'], ['target_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs_placements',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('placement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('program_id', 'placement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programs_placements')
    op.drop_table('program_target_lists')
    op.drop_table('programs')
    op.drop_table('campaigns')
    op.drop_table('contracts')
    op.drop_table('client_target_lists')
    op.drop_table('target_lists')
    op.drop_table('placements')
    op.drop_table('clients')
    # ### end Alembic commands ###
